baseURL = 'https://gfbarbieri.github.io/'
languageCode = 'en-us'
title = 'Greg Barbieri'

[author]
  name = "Greg Barbieri"
  homepage = "gfbarbieri.com"

[based]
  name = "Chris Albon"
  homepage = "https://chrisalbon.com"

[markup]
  [markup.highlight]
    defaultMarkdownHandler = 'goldmark'
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'friendly'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
